/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ads.pi.telas;

import ads.pi.dietas.Dieta1;
import ads.pi.dietas.Dieta2;
import ads.pi.dietas.Dieta3;
import ads.pi.usuario.Usuario;
import ads.pi.usuario.UsuarioDAO;
import static ads.pi.usuario.Usuario_.id;
import exercicios.Ex1;
import exercicios.Ex2;
import exercicios.Ex3;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author LABORATORIO 01
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Usuario usuario = new Usuario();
    UsuarioDAO dao = new UsuarioDAO();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        tfIMC.setText(String.valueOf(calculoIMC()));
        preencherCampos();
        tfData.setText(getDateTime());
    }
    
    public void preencherCampos(){
        Usuario usuario = Usuario.usuarioLogado;
        
        tfAltura.setText(String.valueOf(usuario.getAltura()));
        tfPeso.setText(String.valueOf(usuario.getPeso()));
        tfNome.setText(usuario.getNome());
       //a linguagem do html permite que formatemos o texto como quisermos 
        if(calculoIMC() < 16){
            tfRec1.setText("<html> O seu indice de massa corporal está muito <br />"
                    + " baixo, nosso aplicativo não pode ajudá-lo. <br /> "        
                    + "Recomendamos que procure ajuda médica <html>");
        }else if(calculoIMC() > 40){                                                    ///QUE MIZERIA ÉSSA?
            tfRec1.setText("<htm> O seu indice de massa corporal está muito <br />"
                    + " alto, nosso aplicativo não pode ajudá-lo. <br />"
                    + " Recomendamos que procure ajuda médica.<html>");
        }else{
            tfRec1.setText("");
        }
    }
    
    private String getDateTime() { 
	DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); 
	Date date = new Date(); 
	return dateFormat.format(date); 
}
    
    public double calculoIMC(){
        double IMC;
        
        
        Usuario usuario = Usuario.usuarioLogado;
        
        IMC = usuario.getPeso() / (usuario.getAltura() * usuario.getAltura());
        
        
        return IMC;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfIMC = new javax.swing.JLabel();
        tfNome = new javax.swing.JLabel();
        tfAltura = new javax.swing.JLabel();
        tfPeso = new javax.swing.JLabel();
        tfRec1 = new javax.swing.JLabel();
        btnDietas = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnExer = new javax.swing.JButton();
        tfData = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfIMC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfIMC.setText("IMC");
        getContentPane().add(tfIMC);
        tfIMC.setBounds(190, 310, 44, 17);

        tfNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNome.setText("Nome");
        getContentPane().add(tfNome);
        tfNome.setBounds(180, 150, 290, 25);

        tfAltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tfAltura);
        tfAltura.setBounds(180, 230, 80, 20);

        tfPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tfPeso);
        tfPeso.setBounds(390, 230, 80, 20);

        tfRec1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfRec1.setText("Recomendação");
        tfRec1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(tfRec1);
        tfRec1.setBounds(610, 190, 440, 290);

        btnDietas.setBackground(new java.awt.Color(255, 102, 51));
        btnDietas.setForeground(new java.awt.Color(255, 255, 255));
        btnDietas.setText("Ver Dietas");
        btnDietas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDietasActionPerformed(evt);
            }
        });
        getContentPane().add(btnDietas);
        btnDietas.setBounds(760, 550, 81, 23);

        btnVoltar.setBackground(new java.awt.Color(255, 102, 51));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(660, 550, 61, 23);

        btnExer.setBackground(new java.awt.Color(255, 102, 51));
        btnExer.setForeground(new java.awt.Color(255, 255, 255));
        btnExer.setText("Ver Exercícios");
        btnExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExerActionPerformed(evt);
            }
        });
        getContentPane().add(btnExer);
        btnExer.setBounds(880, 550, 99, 23);

        tfData.setText("DATA");
        getContentPane().add(tfData);
        tfData.setBounds(30, 10, 184, 22);

        btnAtualizar.setText("Atualizar Informações");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(200, 370, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ads/pi/artefatos/tela_principal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDietasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDietasActionPerformed
        if(calculoIMC() < 16){
            JOptionPane.showMessageDialog(null, "<html> O seu indice de massa corporal está muito <br />"
                    + " baixo, nosso aplicativo não pode ajudá-lo. <br /> "
                    + "Recomendamos que procure ajuda médica <html>");
        }else if(calculoIMC() > 40){
            JOptionPane.showMessageDialog(null, "<htm> O seu indice de massa corporal está muito <br />"
                    + " alto, nosso aplicativo não pode ajudá-lo. <br />"
                    + " Recomendamos que procure ajuda médica.<html>");
        }else{
            if(calculoIMC() >= 16 && calculoIMC() < 24){
            Dieta1 d = new Dieta1();
            d.setVisible(true);
        }else if(calculoIMC() >= 24 && calculoIMC() < 32){
            Dieta2 d = new Dieta2();
            d.setVisible(true);
        }else if(calculoIMC() >= 32 && calculoIMC() < 40){
            Dieta3 d = new Dieta3();
            d.setVisible(true);
        }
        }
    }//GEN-LAST:event_btnDietasActionPerformed
        
            
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaLogin telal = new TelaLogin();
        telal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExerActionPerformed
         if(calculoIMC() < 16){
            JOptionPane.showMessageDialog(null, "<html> O seu Indíce de Massa Corporal está muito <br /> baixo, nosso aplicativo não pode "
                    + "ajudá-lo. Recomendamos que procure ajuda médica.");
        }else if(calculoIMC() > 40){
            JOptionPane.showMessageDialog(null, "<html> O seu Indíce de Massa Corporal está muito alto <br />, nosso aplicativo não pode "
                    + "ajudá-lo. Recomendamos que procure ajuda médica.");
        }else{
            if(calculoIMC() >= 16 && calculoIMC() < 24){
            Ex1 e = new Ex1();
            e.setVisible(true);
        }else if(calculoIMC() >= 24 && calculoIMC() < 32){
            Ex2 e = new Ex2();
            e.setVisible(true);
        }else if(calculoIMC() >= 32 && calculoIMC() < 40){
            Ex3 e = new Ex3();
            e.setVisible(true);
        }
        }
    }//GEN-LAST:event_btnExerActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
            int id = usuario.getId();
           
           TelaPessoa tela = new TelaPessoa();
           tela.carregarUsuario(usuario);
           tela.setVisible(true);
           dispose();

    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDietas;
    private javax.swing.JButton btnExer;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tfAltura;
    private javax.swing.JLabel tfData;
    private javax.swing.JLabel tfIMC;
    private javax.swing.JLabel tfNome;
    private javax.swing.JLabel tfPeso;
    private javax.swing.JLabel tfRec1;
    // End of variables declaration//GEN-END:variables
}
