/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ads.pi.telas;

import ads.pi.dietas.Dieta1;
import ads.pi.dietas.Dieta2;
import ads.pi.dietas.Dieta3;
import ads.pi.usuario.Usuario;
import ads.pi.usuario.UsuarioDAO;
import static ads.pi.usuario.Usuario_.id;
import exercicios.Ex1;
import exercicios.Ex2;
import exercicios.Ex3;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LABORATORIO 01
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Usuario usuario = new Usuario();
    UsuarioDAO dao = new UsuarioDAO();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        tfIMC.setText(String.valueOf(calculoIMC()));
        preencherCampos();
        tfData.setText(getDateTime());
    }

    public void preencherCampos() {
        Usuario usuario = Usuario.usuarioLogado;

        tfAltura.setText(String.valueOf(usuario.getAltura()));
        tfPeso.setText(String.valueOf(usuario.getPeso()));
        tfNome.setText(usuario.getNome());

        //a linguagem do html permite que formatemos o texto como quisermos 
        if (calculoIMC() < 16) {
            tfRec1.setText("<html> O seu indice de massa corporal está muito <br />"
                    + " baixo, nosso aplicativo não pode ajudá-lo. <br /> "
                    + "Recomendamos que procure ajuda médica <html>");
        } else if (calculoIMC() > 40) {                                                    ///QUE MIZERIA ÉSSA?
            tfRec1.setText("<htm> O seu indice de massa corporal está muito <br />"
                    + " alto, nosso aplicativo não pode ajudá-lo. <br />"
                    + " Recomendamos que procure ajuda médica.<html>");
        } else {
            tfRec1.setText("Nenhuma Recomendação para Você, Mas Sempre procure"
                    + "um Médico!");
        }
    }

    private String getDateTime() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();
        return dateFormat.format(date);
    }

    public double calculoIMC() {
        double IMC;

        Usuario usuario = Usuario.usuarioLogado;

        IMC = usuario.getPeso() / (usuario.getAltura() * usuario.getAltura());

        return IMC;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfIMC = new javax.swing.JLabel();
        tfNome = new javax.swing.JLabel();
        tfRec1 = new javax.swing.JLabel();
        btnDietas = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnExer = new javax.swing.JButton();
        tfData = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        tfPeso = new javax.swing.JTextField();
        tfAltura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1090, 630));
        getContentPane().setLayout(null);

        tfIMC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfIMC.setText("IMC");
        getContentPane().add(tfIMC);
        tfIMC.setBounds(190, 310, 44, 17);

        tfNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNome.setText("Nome");
        getContentPane().add(tfNome);
        tfNome.setBounds(180, 150, 290, 25);

        tfRec1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfRec1.setText("Nenhuma Recomendação para Você!");
        tfRec1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(tfRec1);
        tfRec1.setBounds(590, 180, 440, 290);

        btnDietas.setBackground(new java.awt.Color(255, 102, 51));
        btnDietas.setForeground(new java.awt.Color(255, 255, 255));
        btnDietas.setText("Ver Dietas");
        btnDietas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDietasActionPerformed(evt);
            }
        });
        getContentPane().add(btnDietas);
        btnDietas.setBounds(760, 550, 81, 23);

        btnSair.setBackground(new java.awt.Color(255, 102, 51));
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(660, 550, 51, 23);

        btnExer.setBackground(new java.awt.Color(255, 102, 51));
        btnExer.setForeground(new java.awt.Color(255, 255, 255));
        btnExer.setText("Ver Exercícios");
        btnExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExerActionPerformed(evt);
            }
        });
        getContentPane().add(btnExer);
        btnExer.setBounds(880, 550, 99, 23);

        tfData.setText("DATA");
        getContentPane().add(tfData);
        tfData.setBounds(30, 10, 184, 22);

        btnAtualizar.setText("Atualizar Informações");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(200, 370, 160, 30);

        tfPeso.setForeground(new java.awt.Color(255, 130, 0));
        tfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoActionPerformed(evt);
            }
        });
        getContentPane().add(tfPeso);
        tfPeso.setBounds(390, 220, 90, 50);

        tfAltura.setForeground(new java.awt.Color(255, 130, 0));
        tfAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlturaActionPerformed(evt);
            }
        });
        getContentPane().add(tfAltura);
        tfAltura.setBounds(180, 220, 90, 50);

        jLabel2.setText("Você pode Atualizar sua Altura e seu Peso conforme sua evolução !");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 190, 390, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ads/pi/artefatos/tela_principal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDietasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDietasActionPerformed
        if (calculoIMC() < 16) {
            JOptionPane.showMessageDialog(null, "<html> O seu indice de massa corporal está muito <br />"
                    + " baixo, nosso aplicativo não pode ajudá-lo. <br /> "
                    + "Recomendamos que procure ajuda médica <html>");
        } else if (calculoIMC() > 40) {
            JOptionPane.showMessageDialog(null, "<htm> O seu indice de massa corporal está muito <br />"
                    + " alto, nosso aplicativo não pode ajudá-lo. <br />"
                    + " Recomendamos que procure ajuda médica.<html>");
        } else {
            if (calculoIMC() >= 16 && calculoIMC() < 24) {
                try {
                    Process p = Runtime.getRuntime().exec("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe file:///C:/Program%20Files/ProjetoInter/data/dieta1.pdf");
                } catch (IOException ex) { //
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (calculoIMC() >= 24 && calculoIMC() < 32) {
                 try {
                    Process p = Runtime.getRuntime().exec("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe file:///C:/Program%20Files/ProjetoInter/data/dieta2.pdf");
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (calculoIMC() >= 32 && calculoIMC() < 40) {
                 try {
                    Process p = Runtime.getRuntime().exec("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe file:///C:/Program%20Files/ProjetoInter/data/dieta3.pdf");
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnDietasActionPerformed


    private void btnExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExerActionPerformed
        if (calculoIMC() < 16) {
            JOptionPane.showMessageDialog(null, "<html> O seu Indíce de Massa Corporal está muito <br /> baixo, nosso aplicativo não pode "
                    + "ajudá-lo. Recomendamos que procure ajuda médica.");
        } else if (calculoIMC() > 40) {
            JOptionPane.showMessageDialog(null, "<html> O seu Indíce de Massa Corporal está muito alto <br />, nosso aplicativo não pode "
                    + "ajudá-lo. Recomendamos que procure ajuda médica.");
        } else {
            if (calculoIMC() >= 16 && calculoIMC() < 24) {
                 try {
                    Process p = Runtime.getRuntime().exec("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe file:///C:/Program%20Files/ProjetoInter/data/treino1.pdf");
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (calculoIMC() >= 24 && calculoIMC() < 32) {
                JOptionPane.showMessageDialog(null, "Para o seu tipo fisico não temos um treino especifico, somente dieta");
            } else if (calculoIMC() >= 32 && calculoIMC() < 40) {
                 try {
                    Process p = Runtime.getRuntime().exec("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe file:///C:/Program%20Files/ProjetoInter/data/treino3.pdf");
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnExerActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Usuario usl = Usuario.usuarioLogado;
         if (tfAltura.getText().isEmpty()
                 || tfPeso.getText().isEmpty())
                 {

            JOptionPane.showMessageDialog(null, "Preencha todos os Campos");
            
        } else {

           
            usl.setPeso(Double.parseDouble(tfPeso.getText()));
            usl.setAltura(Double.parseDouble(tfAltura.getText()));
           

            dao.salvarUsuario(usl);
             JOptionPane.showMessageDialog(null, "É necessario que Faça o Login novamente!");
            TelaLogin telal = new TelaLogin();
            telal.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoActionPerformed

    private void tfAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlturaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        TelaLogin telal = new TelaLogin();
        telal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDietas;
    private javax.swing.JButton btnExer;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JLabel tfData;
    private javax.swing.JLabel tfIMC;
    private javax.swing.JLabel tfNome;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JLabel tfRec1;
    // End of variables declaration//GEN-END:variables
}
