/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ads.pi.telas;

import ads.pi.usuario.UsuarioDAO;
import ads.pi.usuario.Usuario;
import javax.swing.JOptionPane;
/**
 *
 * @author Marlon Santana dos S
 */
public class TelaPessoa extends javax.swing.JFrame {


    UsuarioDAO dao = new UsuarioDAO();
    Usuario usuario = new Usuario();
    TelaCadastro telac = new TelaCadastro();
    
    /**
     * Creates new form TelaInicial
     */
    public TelaPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        tfIdade = new javax.swing.JTextField();
        tsFeminino = new javax.swing.JRadioButton();
        tfPeso = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        tfAltura = new javax.swing.JTextField();
        tsMasculino = new javax.swing.JRadioButton();
        tfNome = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TELA DE LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfIdade.setForeground(new java.awt.Color(255, 130, 5));
        tfIdade.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tfIdade.setSelectionColor(new java.awt.Color(255, 255, 255));
        tfIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(tfIdade);
        tfIdade.setBounds(460, 220, 70, 30);

        tsFeminino.setBackground(new java.awt.Color(255, 255, 255));
        tsFeminino.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tsFeminino.setForeground(new java.awt.Color(255, 130, 5));
        tsFeminino.setText("Feminino");
        tsFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsFemininoActionPerformed(evt);
            }
        });
        getContentPane().add(tsFeminino);
        tsFeminino.setBounds(570, 310, 70, 20);

        tfPeso.setForeground(new java.awt.Color(255, 130, 5));
        tfPeso.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tfPeso.setSelectionColor(new java.awt.Color(255, 255, 255));
        tfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoActionPerformed(evt);
            }
        });
        getContentPane().add(tfPeso);
        tfPeso.setBounds(630, 220, 60, 30);

        btnSalvar.setBackground(new java.awt.Color(255, 130, 5));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(490, 356, 120, 40);

        tfAltura.setForeground(new java.awt.Color(255, 130, 5));
        tfAltura.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tfAltura.setSelectionColor(new java.awt.Color(255, 255, 255));
        tfAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlturaActionPerformed(evt);
            }
        });
        getContentPane().add(tfAltura);
        tfAltura.setBounds(520, 270, 100, 30);

        tsMasculino.setBackground(new java.awt.Color(255, 255, 255));
        tsMasculino.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tsMasculino.setForeground(new java.awt.Color(255, 130, 5));
        tsMasculino.setText("Masculino");
        tsMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsMasculinoActionPerformed(evt);
            }
        });
        getContentPane().add(tsMasculino);
        tsMasculino.setBounds(500, 310, 69, 20);

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome);
        tfNome.setBounds(430, 120, 270, 30);
        getContentPane().add(tfEmail);
        tfEmail.setBounds(430, 170, 270, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ads/pi/artefatos/tela_cadastro_dadospessoais.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 720, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void tsMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsMasculinoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       usuario.setNome(tfNome.getText());
       usuario.setEmail(tfNome.getText());
        usuario.setUsuario(telac.user);
        usuario.setSenha(telac.senha);
        usuario.setIdade(Integer.parseInt(tfIdade.getText()));
        usuario.setPeso(Double.parseDouble(tfPeso.getText()));
        usuario.setAltura(Double.parseDouble(tfAltura.getText()));
        

        if(tsMasculino.isEnabled() & tsFeminino.isEnabled()){
            usuario.setSexo(false);
        }else{
            
            JOptionPane.showMessageDialog(null, "Seleciono apenas Um sexo");
        }
        dao.salvarUsuario(usuario);
        TelaPrincipal telap = new TelaPrincipal();
        telap.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tfAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlturaActionPerformed

    private void tfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoActionPerformed

    private void tfIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdadeActionPerformed

    private void tsFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsFemininoActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JRadioButton tsFeminino;
    private javax.swing.JRadioButton tsMasculino;
    // End of variables declaration//GEN-END:variables
}
